### PR TITLE
fix closing generic with open brace same line caused by Prettier

### LINKED ISSUE #13: Linting fails for constructor of generic type after prettier multi-line format
Prettier formats some generic type definitions by placing the generic constraints on multiple lines.

This causes tslint-lines-between-class-members to fail linting. 

The error is `must have 1 new line(s) between class methods, see docs for how to configure` which appears on the `constructor() {` line.

I believe this is due to how you are checking the previous line.

Passes
```
export class PermissionsStore extends EntityStore<PermissionsState, Permission> {
  constructor() {
    super();
  }
}
```

Fails
```
export class PermissionsStore extends EntityStore<
  PermissionsState,
  Permission
> {
  constructor() {
    super();
  }
}
```

### PR DESCRIPTION
**Pull request by seangwright**
Fixes #13 

I couldn't get `npm run lint` to pass - it keeps checking `node_modules`, I think the command options might be wrong?

Also most of the `fix` tests failed for me even though I didn't change anything that should effect them.

### CODE REVIEW

**Comment by seangwright** [comment]
I'm seeing more and more cases where the `constructor()` line fails validation because of how Prettier can format the class definition.

Maybe checking if the current line is a constructor is a better option than checking the previous line?

**Comment by chinchiheather** [comment]
Hi, sorry, I have been absent for quite a while, just working through the issues...

I made some changes so there are conflicts now, but I am happy to try and implement this fix if you don't want to anymore. I added a contributing.md which may help you with your issues around linting/testing

With regards to just checking if the line is a constructor, I'm not sure that will work as we don't want to just ignore checking constructor functions, do you have any other examples where Prettier has  formatted it in a way that causes failures? I am happy to try and fix those too

**Comment by seangwright** [comment]
It seems mostly to be in the situations where the class definition line gets really long and breaks into 2 or more.

I'll take a look at the PR again soon.

Thanks!

**Comment by chinchiheather** [comment]
I ended up fixing this myself as it was raised by someone else too.

Thanks for raising your PR though 🙂

**Pull request closed without merging**
